# Flask-specific config
CACHE_TYPE: MemcachedCache
CACHE_DEFAULT_TIMEOUT: 300
CACHE_KEY_PREFIX: wmcz-test-otevrenesbirky
CACHE_MEMCACHED_SERVERS:
  - 127.0.0.1

# app-specific config
currentYear: 2024

# Hodnoty musí odpovídat názvů sloupečků v Google Sheetu s daty o sbírkách
currentYearTotalKey: Total 2024
currentYearOnlineKey: Online 2024
currentYearOpenKey: Open 2024

gsheetUrl: https://docs.google.com/spreadsheets/d/1vOeKKAA0y43lL_NE-UVV66IDyjAUGkxsQiHikBn6CwU
